# Generated by Django 4.1.1 on 2023-09-25 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0001_initial'),
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officemodel',
            name='locality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locality.localitymodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='officemodel',
            name='street',
            field=models.CharField(max_length=20),
        ),
    ]
