# Generated by Django 4.1.1 on 2023-09-28 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField()),
                ('state', models.CharField(choices=[('BUENOS_AIRES', 'BUENOS_AIRES'), ('CATAMARCA', 'CATAMARCA'), ('CHACO', 'CHACO'), ('CHUBUT', 'CHUBUT'), ('CORDOBA', 'CORDOBA'), ('CORRIENTES', 'CORRIENTES'), ('ENTRE_RIOS', 'ENTRE_RIOS'), ('FORMOSA', 'FORMOSA'), ('JUJUY', 'JUJUY'), ('LA_PAMPA', 'LA_PAMPA'), ('LA_RIOJA', 'LA_RIOJA'), ('MENDOZA', 'MENDOZA'), ('MISIONES', 'MISIONES'), ('NEUQUEN', 'NEUQUEN'), ('RIO_NEGRO', 'RIO_NEGRO'), ('SALTA', 'SALTA'), ('SAN_JUAN', 'SAN_JUAN'), ('SAN_LUIS', 'SAN_LUIS'), ('SANTA_CRUZ', 'SANTA_CRUZ'), ('SANTA_FE', 'SANTA_FE'), ('SANTIAGO_DEL_ESTERO', 'SANTIAGO_DEL_ESTERO'), ('TIERRA_DEL_FUEGO', 'TIERRA_DEL_FUEGO'), ('TUCUMAN', 'TUCUMAN')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=20)),
                ('house_number', models.CharField(max_length=10)),
                ('note', models.CharField(max_length=255)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.localitymodel')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(help_text='Número de la calle donde vive el cliente', max_length=10)),
                ('street_name', models.CharField(help_text='Nombre de la calle donde vive el cliente', max_length=255)),
                ('house_unit', models.CharField(blank=True, help_text='Número de la casa o departamento', max_length=10, null=True)),
                ('dni', models.CharField(help_text='Número de documento de identidad del cliente', max_length=20)),
                ('phone_code', models.CharField(help_text='Código de área del teléfono del cliente', max_length=10)),
                ('phone_number', models.CharField(help_text='Número de teléfono del cliente', max_length=10)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.localitymodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
