# Generated by Django 4.2.7 on 2024-02-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalorder',
            name='requested_for_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
