# Generated by Django 4.1.1 on 2023-09-28 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=30)),
                ('phone_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('street', models.CharField(max_length=30)),
                ('house_number', models.CharField(max_length=30)),
                ('apartment', models.CharField(max_length=30)),
                ('note', models.TextField()),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.localitymodel')),
            ],
        ),
    ]
