# Generated by Django 4.2.7 on 2024-03-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalorderlineitem',
            name='quantity_sent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
