# Generated by Django 4.2.7 on 2024-03-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_internalorderlineitem_source_office_quantity_after_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorderlineitem',
            name='target_office_quantity_after_receive',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplierorderlineitem',
            name='target_office_quantity_before_receive',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
