# Generated by Django 4.1.1 on 2023-10-06 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_clientmodel_user_clientmodel_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='sku',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='type',
            field=models.CharField(choices=[('ALQUILABLE', 'ALQUILABLE'), ('COMERCIABLE', 'COMERCIABLE')], default='COMERCIABLE', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductSupplierModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.productmodel')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.suppliermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOfficeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='core.officemodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='core.productmodel')),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.brandmodel'),
            preserve_default=False,
        ),
    ]
