# Generated by Django 4.1.1 on 2023-10-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_brandmodel_rename_title_productmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='sku',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
