# Generated by Django 4.2.7 on 2024-03-02 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_user_supplierorderhistory_responsible_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplierOrderLineItem',
            new_name='SupplierOrderItem',
        ),
    ]
