# Generated by Django 4.1.1 on 2023-10-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_productmodel_sku'),
        ('core', '0005_localitymodel_unique_locality'),
    ]

    operations = [
    ]
