# Generated by Django 4.1.1 on 2023-10-12 22:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20231012_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliermodel',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='suppliermodel',
            name='note',
        ),
        migrations.RemoveField(
            model_name='suppliermodel',
            name='street',
        ),
        migrations.AddField(
            model_name='suppliermodel',
            name='house_unit',
            field=models.CharField(blank=True, help_text='Número de la casa o departamento', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='suppliermodel',
            name='street_name',
            field=models.CharField(default='', help_text='Nombre de la calle donde vive el proveedor', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suppliermodel',
            name='house_number',
            field=models.CharField(help_text='Número de la calle donde vive el proveedor', max_length=10),
        ),
        migrations.AlterField(
            model_name='suppliermodel',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.localitymodel'),
        ),
        migrations.AlterField(
            model_name='suppliermodel',
            name='phone_code',
            field=models.CharField(help_text='Código de área del teléfono del proveedor', max_length=10, validators=[django.core.validators.RegexValidator(message='Solo se permiten dígitos.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='suppliermodel',
            name='phone_number',
            field=models.CharField(help_text='Número de teléfono del proveedor', max_length=10, validators=[django.core.validators.RegexValidator(message='Solo se permiten dígitos.', regex='^\\d+$')]),
        ),
    ]
