# Generated by Django 4.2.7 on 2024-03-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_supplierorderlineitem_supplierorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorderhistory',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
