# Generated by Django 4.1.1 on 2023-10-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_suppliermodel_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliermodel',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
