# Generated by Django 4.2.7 on 2024-03-03 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_supplierorderhistory_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracthistory',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contracthistory',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contracthistory',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='core.contract'),
        ),
    ]
