# Generated by Django 4.1.1 on 2023-10-20 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_suppliermodel_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('office_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_orders_branch', to='core.officemodel')),
                ('office_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_orders_destination', to='core.officemodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSupplierModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.officemodel')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.suppliermodel')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_order', to='core.productmodel')),
                ('supplier_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.ordersuppliermodel')),
            ],
        ),
        migrations.CreateModel(
            name='InternalOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(max_length=255)),
                ('internal_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.internalordermodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_order', to='core.productmodel')),
            ],
        ),
    ]
