# Generated by Django 4.1.1 on 2023-10-20 17:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_internalordermodel_ordersuppliermodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completado'), ('CANCELED', 'Cancelado')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='internalordermodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='internalorderproduct',
            name='stock',
        ),
        migrations.AddField(
            model_name='internalordermodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalorderproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internalorderproduct',
            name='quantity_received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internalorderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='core.productmodel'),
        ),
        migrations.AddConstraint(
            model_name='internalorderproduct',
            constraint=models.UniqueConstraint(fields=('product', 'internal_order'), name='unique_product_internal_order'),
        ),
        migrations.AddConstraint(
            model_name='internalorderproduct',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='quantity_must_be_positive'),
        ),
        migrations.AddConstraint(
            model_name='internalorderproduct',
            constraint=models.CheckConstraint(check=models.Q(('quantity_received__gte', 0)), name='quantity_received_must_be_positive'),
        ),
        migrations.AddConstraint(
            model_name='internalorderproduct',
            constraint=models.CheckConstraint(check=models.Q(('quantity_received__lte', models.F('quantity'))), name='quantity_received_must_be_lte_to_quantity'),
        ),
        migrations.AddField(
            model_name='internalorderhistory',
            name='internal_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.internalordermodel'),
        ),
        migrations.AddField(
            model_name='internalorderhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalordermodel',
            name='current_history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_order', to='core.internalorderhistory'),
        ),
    ]
