# Generated by Django 4.2.7 on 2024-03-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_contractitemproductallocation_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='final_deposit_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='first_deposit_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
