# Generated by Django 4.1.1 on 2023-10-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_internalorderhistory_internalorderhistorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officemodel',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
