# Generated by Django 4.1.1 on 2023-10-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_officemodel_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductOfficeModel',
            new_name='ProductStockInOfficeModel',
        ),
    ]
