# Generated by Django 4.1.1 on 2023-10-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_productofficemodel_productstockinofficemodel'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productstockinofficemodel',
            constraint=models.UniqueConstraint(fields=('office', 'product'), name='unique_stock'),
        ),
    ]
