# Generated by Django 4.1.1 on 2023-10-22 04:24

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_purchasehistorymodel_alter_ordersuppliermodel_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalContractHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESUPUESTADO', 'PRESUPUESTADO'), ('CON_DEPOSITO', 'SEÑADO'), ('PAGADO', 'PAGADO'), ('CANCELADO', 'CANCELADO'), ('ACTIVO', 'ACTIVO'), ('FINALIZADO', 'FINALIZADO')], max_length=50)),
            ],
            options={
                'verbose_name': 'Rental Contract History',
                'verbose_name_plural': 'Rental Contract Histories',
            },
        ),
        migrations.CreateModel(
            name='RentalContractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_contracts', to='core.clientmodel')),
                ('current_history', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_rental_contract', to='core.rentalcontracthistorymodel')),
            ],
            options={
                'verbose_name': 'Rental Contract',
                'verbose_name_plural': 'Rental Contracts',
            },
        ),
        migrations.CreateModel(
            name='RentalContractItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('quantity_returned', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_contract_items', to='core.productmodel')),
                ('rental_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_contract_items', to='core.rentalcontractmodel')),
            ],
            options={
                'verbose_name': 'Rental Contract Item',
                'verbose_name_plural': 'Rental Contract Items',
            },
        ),
        migrations.AddField(
            model_name='rentalcontracthistorymodel',
            name='rental_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_contract_history', to='core.rentalcontractmodel'),
        ),
        migrations.AddConstraint(
            model_name='rentalcontractmodel',
            constraint=models.CheckConstraint(check=models.Q(('deposit_amount__gte', 0)), name='deposit_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='rentalcontractmodel',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='total_must_be_positive'),
        ),
        migrations.AddConstraint(
            model_name='rentalcontractmodel',
            constraint=models.CheckConstraint(check=models.Q(('deposit_amount__lte', models.F('total'))), name='deposit_amount_must_be_less_than_total'),
        ),
        migrations.AddConstraint(
            model_name='rentalcontractmodel',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', models.F('deposit_amount'))), name='total_must_be_greater_than_deposit_amount'),
        ),
        migrations.AddConstraint(
            model_name='rentalcontractmodel',
            constraint=models.CheckConstraint(check=models.Q(('total', django.db.models.expressions.CombinedExpression(models.F('deposit_amount'), '+', models.F('payment_amount')))), name='deposit_amount_plus_payment_amount_must_be_equal_to_total'),
        ),
        migrations.AddConstraint(
            model_name='rentalcontractitemmodel',
            constraint=models.UniqueConstraint(fields=('rental_contract', 'product'), name='unique_rental_contract_item'),
        ),
        migrations.AddConstraint(
            model_name='rentalcontractitemmodel',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1)), name='quantity_must_be_greater_than_0'),
        ),
        migrations.AddConstraint(
            model_name='rentalcontractitemmodel',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='rental_contract_item_total_must_be_positive'),
        ),
        migrations.AddConstraint(
            model_name='rentalcontractitemmodel',
            constraint=models.CheckConstraint(check=models.Q(('quantity_returned__lte', models.F('quantity'))), name='quantity_returned_must_be_less_than_quantity'),
        ),
    ]
