# Generated by Django 4.1.1 on 2023-10-23 20:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_rentalcontracthistorymodel_rentalcontractmodel_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rentalcontractmodel",
            name="total_must_be_positive",
        ),
        migrations.RemoveConstraint(
            model_name="rentalcontractmodel",
            name="deposit_amount_must_be_less_than_total",
        ),
        migrations.RemoveConstraint(
            model_name="rentalcontractmodel",
            name="deposit_amount_positive",
        ),
        migrations.CreateModel(
            name="ServiceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.RemoveConstraint(
            model_name="rentalcontractitemmodel",
            name="unique_rental_contract_item",
        ),
        migrations.RemoveConstraint(
            model_name="rentalcontractitemmodel",
            name="rental_contract_item_total_must_be_positive",
        ),
        migrations.RemoveConstraint(
            model_name="rentalcontractitemmodel",
            name="quantity_returned_must_be_less_than_quantity",
        ),
        migrations.RemoveConstraint(
            model_name="rentalcontractmodel",
            name="total_must_be_greater_than_deposit_amount",
        ),
        migrations.RemoveConstraint(
            model_name="rentalcontractmodel",
            name="deposit_amount_plus_payment_amount_must_be_equal_to_total",
        ),
        migrations.RemoveField(
            model_name="rentalcontractmodel",
            name="deposit_amount",
        ),
        migrations.RemoveField(
            model_name="rentalcontractmodel",
            name="payment_amount",
        ),
        migrations.AddField(
            model_name="rentalcontractitemmodel",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=1, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rentalcontractitemmodel",
            name="service_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="rentalcontractitemmodel",
            name="service_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="rentalcontractmodel",
            name="contract_end_datetime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 23, 20, 15, 3, 842660, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rentalcontractmodel",
            name="contract_start_datetime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 23, 20, 15, 9, 119513, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rentalcontractmodel",
            name="expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentalcontractmodel",
            name="has_payed_deposit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rentalcontractmodel",
            name="has_payed_remaining_amount",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rentalcontractmodel",
            name="house_number",
            field=models.CharField(
                default=1,
                help_text="Número de la calle donde vive el cliente",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rentalcontractmodel",
            name="house_unit",
            field=models.CharField(
                blank=True,
                help_text="Número de la casa o departamento",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rentalcontractmodel",
            name="locality",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental_contracts",
                to="core.localitymodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rentalcontractmodel",
            name="office",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental_contracts",
                to="core.officemodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rentalcontractmodel",
            name="street_name",
            field=models.CharField(
                default=1,
                help_text="Nombre de la calle donde vive el cliente",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="purchasehistorymodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("CANCELED", "Cancelado"),
                    ("PAID", "Pagado"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="rentalcontracthistorymodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESUPUESTADO", "PRESUPUESTADO"),
                    ("CON_DEPOSITO", "SEÑADO"),
                    ("PAGADO", "PAGADO"),
                    ("CANCELADO", "CANCELADO"),
                    ("ACTIVO", "ACTIVO"),
                    ("VENCIDO", "VENCIDO"),
                    ("FINALIZADO", "FINALIZADO"),
                    ("DEVOLUCION_EXITOSA", "DEVOLUCION EXITOSA"),
                    ("DEVOLUCION_FALLIDA", "DEVOLUCION FALLIDA"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="rentalcontractitemmodel",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental_contract_items",
                to="core.servicemodel",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentalcontractitemmodel",
            constraint=models.UniqueConstraint(
                fields=("rental_contract", "product", "service"),
                name="unique_rental_contract_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentalcontractitemmodel",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity_returned__lte", models.F("quantity"))),
                name="quantity_returned_must_be_lte_quantity",
            ),
        ),
        migrations.AddField(
            model_name="servicemodel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="core.productmodel",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicemodel",
            constraint=models.UniqueConstraint(
                fields=("product", "name"), name="unique_service_name_by_product"
            ),
        ),
    ]
