# Generated by Django 4.1.1 on 2023-10-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_productmodel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='productmodel',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='price_must_be_greater_than_0'),
        ),
        migrations.AddConstraint(
            model_name='servicemodel',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='price_gte_0'),
        ),
    ]
