# Generated by Django 4.1.1 on 2023-10-25 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_alter_productmodel_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrderHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completado'), ('CANCELED', 'Cancelado')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordersuppliermodel',
            name='office',
        ),
        migrations.RemoveField(
            model_name='ordersuppliermodel',
            name='supplier',
        ),
        migrations.RemoveConstraint(
            model_name='internalorderproduct',
            name='unique_product_internal_order',
        ),
        migrations.RemoveConstraint(
            model_name='internalorderproduct',
            name='quantity_must_be_positive',
        ),
        migrations.RemoveConstraint(
            model_name='internalorderproduct',
            name='quantity_received_must_be_positive',
        ),
        migrations.RemoveConstraint(
            model_name='internalorderproduct',
            name='quantity_received_must_be_lte_to_quantity',
        ),
        migrations.RemoveField(
            model_name='supplierorderproduct',
            name='cant',
        ),
        migrations.AddField(
            model_name='supplierorderproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplierorderproduct',
            name='quantity_received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplierorderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_supplier_orders', to='core.productmodel'),
        ),
        migrations.AddConstraint(
            model_name='internalorderproduct',
            constraint=models.UniqueConstraint(fields=('product', 'internal_order'), name='internal_order_unique_product'),
        ),
        migrations.AddConstraint(
            model_name='internalorderproduct',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='internal_order_quantity_must_be_positive'),
        ),
        migrations.AddConstraint(
            model_name='internalorderproduct',
            constraint=models.CheckConstraint(check=models.Q(('quantity_received__gte', 0)), name='internal_order_quantity_received_must_be_positive'),
        ),
        migrations.AddConstraint(
            model_name='internalorderproduct',
            constraint=models.CheckConstraint(check=models.Q(('quantity_received__lte', models.F('quantity'))), name='internal_order_quantity_received_must_be_lte_to_quantity'),
        ),
        migrations.AddConstraint(
            model_name='supplierorderproduct',
            constraint=models.UniqueConstraint(fields=('product', 'supplier_order'), name='order_supplier_unique_product'),
        ),
        migrations.AddConstraint(
            model_name='supplierorderproduct',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='order_supplier_quantity_must_be_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierorderproduct',
            constraint=models.CheckConstraint(check=models.Q(('quantity_received__gte', 0)), name='order_supplier_quantity_received_must_be_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierorderproduct',
            constraint=models.CheckConstraint(check=models.Q(('quantity_received__lte', models.F('quantity'))), name='order_supplier_quantity_received_must_be_lte_to_quantity'),
        ),
        migrations.AddField(
            model_name='supplierordermodel',
            name='current_history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_order', to='core.supplierorderhistorymodel'),
        ),
        migrations.AddField(
            model_name='supplierordermodel',
            name='office_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders_destination', to='core.officemodel'),
        ),
        migrations.AddField(
            model_name='supplierordermodel',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders_branch', to='core.suppliermodel'),
        ),
        migrations.AddField(
            model_name='supplierorderhistorymodel',
            name='supplier_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.supplierordermodel'),
        ),
        migrations.AddField(
            model_name='supplierorderhistorymodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplierorderproduct',
            name='supplier_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers_orders', to='core.supplierordermodel'),
        ),
        migrations.DeleteModel(
            name='OrderSupplierModel',
        ),
    ]
