# Generated by Django 4.1.1 on 2023-10-25 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_supplierorderhistorymodel_supplierordermodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierordermodel',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierorderproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierorderproduct',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierorderproduct',
            name='supplier_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.supplierordermodel'),
        ),
    ]
