# Generated by Django 4.1.1 on 2023-11-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_supplierordermodel_total_supplierorderproduct_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceModel',
            new_name='ProductServiceModel',
        ),
    ]
