# Generated by Django 4.1.1 on 2023-11-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_purchasehistorymodel_purchase_and_more'),
        ('core', '0022_rename_servicemodel_productservicemodel'),
    ]

    operations = [
    ]
