# Generated by Django 4.1.1 on 2023-11-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_productservicemodel_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalcontractmodel',
            name='date_created',
        ),
    ]
