# Generated by Django 4.2.7 on 2023-11-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_rentalcontractmodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcontractmodel',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
