# Generated by Django 4.2.7 on 2023-11-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_purchasemodel_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitemmodel',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
