# Generated by Django 4.2.7 on 2023-11-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_supplierordermodel_total_supplierorderproduct_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierorderhistorymodel',
            name='date',
        ),
    ]
