# Generated by Django 4.2.7 on 2023-11-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_supplierorderhistorymodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierordermodel',
            name='date_created',
        ),
    ]
