# Generated by Django 4.2.7 on 2023-11-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_internalordermodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcontractitemmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rentalcontractitemmodel',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
