# Generated by Django 4.2.7 on 2023-11-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_rentalcontractitemmodel_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasemodel',
            name='date',
        ),
    ]
