# Generated by Django 4.2.7 on 2023-11-30 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_purchasemodel_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InternalOrderProduct',
            new_name='InternalOrderProductModel',
        ),
        migrations.RenameModel(
            old_name='SupplierOrderProduct',
            new_name='SupplierOrderProductModel',
        ),
    ]
