# Generated by Django 4.2.7 on 2023-11-30 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_rename_internalorderproduct_internalorderproductmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemodel',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.officemodel'),
            preserve_default=False,
        ),
    ]
