# Generated by Django 4.2.7 on 2023-11-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_purchasemodel_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstockinofficemodel',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
