# Generated by Django 4.2.7 on 2023-12-01 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_productstockinofficemodel_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOfficeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='core.employeemodel')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.officemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
