# Generated by Django 4.2.7 on 2023-12-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_employeeofficemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalcontractmodel',
            name='has_payed_deposit',
        ),
        migrations.RemoveField(
            model_name='rentalcontractmodel',
            name='has_payed_remaining_amount',
        ),
    ]
