# Generated by Django 4.2.7 on 2024-01-10 20:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0043_adminmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontractmodel',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rental_contracts_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalcontractmodel',
            name='number_of_rental_days',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productservicemodel',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productsuppliermodel',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseitemmodel',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaseitemmodel',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitemmodel',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalcontractitemmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalcontractitemmodel',
            name='service_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalcontractitemmodel',
            name='service_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalcontractitemmodel',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalcontractmodel',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierordermodel',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierorderproductmodel',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplierorderproductmodel',
            name='total',
            field=models.IntegerField(blank=True),
        ),
        migrations.CreateModel(
            name='RentalContractItemOfficeOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices_orders', to='core.rentalcontractitemmodel')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_contract_items_offices_orders', to='core.officemodel')),
            ],
            options={
                'unique_together': {('office', 'item')},
            },
        ),
        migrations.AddField(
            model_name='internalordermodel',
            name='rental_contract_item_office_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_order', to='core.rentalcontractitemofficeordermodel'),
        ),
    ]
