# Generated by Django 4.2.7 on 2024-01-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_rentalcontractmodel_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalcontractitemmodel',
            name='service_total',
        ),
    ]
