# Generated by Django 4.2.7 on 2024-01-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_rentalcontractitemmodel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontractitemmodel',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rentalcontractitemmodel',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
