# Generated by Django 4.2.7 on 2024-01-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_rentalcontractitemmodel_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitemmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseitemmodel',
            name='total',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='total',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rentalcontractitemmodel',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rentalcontractmodel',
            name='total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
