# Generated by Django 4.1.1 on 2023-09-25 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(help_text='Número de la calle donde vive el cliente', max_length=10)),
                ('street_name', models.CharField(help_text='Nombre de la calle donde vive el cliente', max_length=255)),
                ('house_unit', models.CharField(blank=True, help_text='Número de la casa o departamento', max_length=10, null=True)),
                ('dni', models.CharField(help_text='Número de documento de identidad del cliente', max_length=20)),
                ('phone_code', models.CharField(help_text='Código de área del teléfono del cliente', max_length=10)),
                ('phone_number', models.CharField(help_text='Número de teléfono del cliente', max_length=10)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='locality.localitymodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
