# Generated by Django 4.1.1 on 2023-09-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField()),
                ('state', models.CharField(choices=[('BUENOS_AIRES', 'BUENOS_AIRES'), ('CATAMARCA', 'CATAMARCA'), ('CHACO', 'CHACO'), ('CHUBUT', 'CHUBUT'), ('CORDOBA', 'CORDOBA'), ('CORRIENTES', 'CORRIENTES'), ('ENTRE_RIOS', 'ENTRE_RIOS'), ('FORMOSA', 'FORMOSA'), ('JUJUY', 'JUJUY'), ('LA_PAMPA', 'LA_PAMPA'), ('LA_RIOJA', 'LA_RIOJA'), ('MENDOZA', 'MENDOZA'), ('MISIONES', 'MISIONES'), ('NEUQUEN', 'NEUQUEN'), ('RIO_NEGRO', 'RIO_NEGRO'), ('SALTA', 'SALTA'), ('SAN_JUAN', 'SAN_JUAN'), ('SAN_LUIS', 'SAN_LUIS'), ('SANTA_CRUZ', 'SANTA_CRUZ'), ('SANTA_FE', 'SANTA_FE'), ('SANTIAGO_DEL_ESTERO', 'SANTIAGO_DEL_ESTERO'), ('TIERRA_DEL_FUEGO', 'TIERRA_DEL_FUEGO'), ('TUCUMAN', 'TUCUMAN')], max_length=30)),
            ],
        ),
    ]
