# Generated by Django 4.2.7 on 2024-03-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='token_version',
            field=models.IntegerField(default=0),
        ),
    ]
